import socket
import sys
import json
from subprocess import call
import pymongo
import time
from watchdog.observers import Observer
from watchdog.events import FileSystemEvent, FileSystemEventHandler

class MyFileHandler(FileSystemEventHandler):
  def __init__(self, target_file_path):
    self.target_file_path = target_file_path
    self.flag_done = False

  def process_done(self):
    return self.flag_done

  def on_created(self, event):
    if event.src_path == self.target_file_path:
      self.flag_done = True

  def on_modified(self, event):
    if event.src_path == self.target_file_path:
      self.flag_done = True



def read_json(target_path):
  with open(target_path, 'r') as json_data:
    response_data = json.load(json_data)
  return response_data 

def update_db():
  pass  

def call_searchbin(query):
  # extract and normalize building name - no spaces, all lowercase
  building = ''.join(query['building'].split(' ')).lower()
  # extract usage in kilowatts
  usagekW = query['usagekW']

  if usagekW < 37:
    binNum = 1
  elif usagekW <= 55:
    binNum = 2
  elif usagekW <= 74:
    binNum = 3
  elif usagekW <= 92:
    binNum = 4
  elif usagekW <= 111:
    binNum = 5
  else:
    binNum = 5
    #TODO: add error case, inform user that max usage is 111 kW

  # wait until output json file is generated by executable matlab
  observer_path = '.'
  target_path = './response_HuntsmanHall.json' #TODO: update based on building name
  observer = Observer()
  handler = MyFileHandler(target_path)
  observer.schedule(handler, observer_path)
  observer.start()

  # use subprocess.call to execute query 
  scriptName = ''.join(['run_searchbin_', building, '.sh'])
  scriptPath = '/'.join(['.', 'MATLAB', 'Penn-Analytics', scriptName])
  call(['sudo', scriptPath, str(binNum)])

  # TODO: wait for query to complete and output file to be created/modified
  while handler.process_done == False:
    time.sleep(1)
  observer.stop()
  observer.join()

  # TODO: read query output file
  response = read_json(target_path)

  # TODO: update DB with query result to update graphical output with pymongo.MongoClient
  # TODO: return content for vocal response 
  return response

def start_server(ipaddr, port):
  # Create a TCP/IP socket
  sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

  # Bind the socket to the port
  server_address = (ipaddr, port)
  print >>sys.stderr, 'starting up on %s port %s' % server_address
  sock.bind(server_address)

  # Listen for incoming connections
  sock.listen(1)

  end_flag = '$'

  while True:
    # Wait for a connection
    print >>sys.stderr, 'waiting for a connection'
    connection, client_address = sock.accept()

    try:
      print >>sys.stderr, 'connection from', client_address

      # Receive the data in small chunks and retransmit it
      query_parts= []
      while True:
        data = connection.recv(16)
        print >>sys.stderr, 'received "%s"' % data
        if data:
          # build query from lambda
          query_parts.append(data)
          if end_flag in data:
            break

      print >>sys.stderr, 'no more data from', client_address
      # reconstruct query string
      query_str = ''.join([s for s in query_parts])
      query_str = query_str[0:-1]
      # parse query type and parameters
      query = json.loads(query_str)
      print "received query:", query
      
      if query['type'] == 1:
        response = call_searchbin(query)

      response_str = json.dumps(response) + end_flag
      connection.sendall(response_str)
      print "sent:", response_str

    finally:
      # Clean up the connection
      connection.close()

if __name__ == "__main__":
  sys.exit(start_server('0.0.0.0', 9000))
