function [ predictedkW ] = kwprediction(lighting,thermostat,chiller)
%{

This function take the following inputs:

lighting = must be a value between 0 and 1. The value corresponds to the 
ratio of lighting power which is ON, or how many lights need to be dimmed
1 means 100% lighting. Ideally this value should not be belwo 0.5 during a 
DR event. 
thermostat = must be a value between 25-29 [C]. 
chiller = must be a value between 6.5-10 [C];

The output is the predicted value in W.

The baseline power consumption is 1.5e6 W

%}

FUNtest_data = coder.load('FUNtest_data.mat');
Tree_data = coder.load('Tree.mat');

XDR = [FUNtest_data.BASEMENTZoneAirTemperatureCTimeStep(2:end),...
    FUNtest_data.HEATSYS1BOILERBoilerOutletTemperatureCTimeStep(2:end),...
    FUNtest_data.COOLSYS1CHILLER1ChillerEvaporatorOutletTemperatureCTimeStep(2:end),...
    FUNtest_data.COOLSYS1CHILLER2ChillerEvaporatorOutletTemperatureCTimeStep(2:end),...
    FUNtest_data.CORE_BOTTOMZoneAirTemperatureCTimeStep(2:end),...
    FUNtest_data.CORE_MIDZoneAirTemperatureCTimeStep(2:end),...
    FUNtest_data.CORE_TOPZoneAirTemperatureCTimeStep(2:end),...
    FUNtest_data.EMScurrentDayOfWeekTimeStep(2:end),...
    FUNtest_data.GROUNDFLOOR_PLENUMZoneAirTemperatureCTimeStep(2:end),...
    FUNtest_data.HTGSETP_SCHScheduleValueTimeStep(2:end),...
    FUNtest_data.HWLOOPTEMPSCHEDULEScheduleValueTimeStep(2:end),...
    FUNtest_data.MIDFLOOR_PLENUMZoneAirTemperatureCTimeStep(2:end),...
    FUNtest_data.EnvironmentSiteOutdoorAirDrybulbTemperatureCTimeStep(2:end),...
    FUNtest_data.EnvironmentSiteOutdoorAirRelativeHumidityTimeStep(2:end),...
    FUNtest_data.EnvironmentSiteOutdoorAirWetbulbTemperatureCTimeStep(2:end),...
    FUNtest_data.PERIMETER_BOT_ZN_1ZoneAirTemperatureCTimeStep(2:end),...
    FUNtest_data.PERIMETER_BOT_ZN_2ZoneAirTemperatureCTimeStep(2:end),...                   
    FUNtest_data.PERIMETER_BOT_ZN_3ZoneAirTemperatureCTimeStep(2:end),...                   
    FUNtest_data.PERIMETER_BOT_ZN_4ZoneAirTemperatureCTimeStep(2:end),...                   
    FUNtest_data.PERIMETER_MID_ZN_1ZoneAirTemperatureCTimeStep(2:end),...                   
    FUNtest_data.PERIMETER_MID_ZN_2ZoneAirTemperatureCTimeStep(2:end),...                   
    FUNtest_data.PERIMETER_MID_ZN_3ZoneAirTemperatureCTimeStep(2:end),...                   
    FUNtest_data.PERIMETER_MID_ZN_4ZoneAirTemperatureCTimeStep(2:end),...                   
    FUNtest_data.PERIMETER_TOP_ZN_1ZoneAirTemperatureCTimeStep(2:end),...                   
    FUNtest_data.PERIMETER_TOP_ZN_2ZoneAirTemperatureCTimeStep(2:end),...                   
    FUNtest_data.PERIMETER_TOP_ZN_3ZoneAirTemperatureCTimeStep(2:end),...                   
    FUNtest_data.PERIMETER_TOP_ZN_4ZoneAirTemperatureCTimeStep(2:end),... 
    FUNtest_data.EMScurrentTimeOfDayTimeStep(2:end),...
    FUNtest_data.TOPFLOOR_PLENUMZoneAirTemperatureCTimeStep(2:end),...
    FUNtest_data.EnvironmentSiteWindDirectiondegTimeStep(2:end),...
    FUNtest_data.EnvironmentSiteWindSpeedmsTimeStep(2:end),...
    FUNtest_data.CLGSETP_SCHScheduleValueTimeStep(2:end), ...
    FUNtest_data.CWLOOPTEMPSCHEDULEScheduleValueTimeStep(2:end),...
    FUNtest_data.BLDG_LIGHT_SCHScheduleValueTimeStep(2:end)];
XDR = round(XDR,2);

YDR = FUNtest_data.WholeBuildingFacilityTotalElectricDemandPowerWTimeStep(2:end);
YDR = round(YDR,-4);

lag_kw = mylagmatrix(YDR,[1,2,3,4,5,6]);
lag_kw_nanidx = find(isnan(lag_kw));
lag_kw(lag_kw_nanidx) = 0;

% Augment training matrix with lagged kw columns
XDR = [XDR,lag_kw];

% row = 400 + randi(400);
% forecast = XDR(row,:);
forecast = XDR(407,:);


forecast(34)=lighting;
forecast(33)=chiller;
forecast(34)=thermostat;

predictedkW = predict(Tree_data.Rforest,forecast);


end